In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import numpy as np

In [9]:
#irisflowers data
iris = load_iris()

In [13]:

iris.target#contains the target so the results (Y)
iris.data #contains the data whiche would be the X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [16]:
data = np.c_[iris.data,iris.target] #concatenate the two array
columns = iris['feature_names'] + ['ResultSpecis'] #featurne name and target which is the species

In [18]:
df = pd.DataFrame(data = data, columns = columns)

In [19]:
df # now we got our dataframe let's separate the X and the target Y

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     ResultSpecis  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  
..            ...  
145           2.0  
146           2.0  
147           2.0  
148           2.0  
149           2.0  

[150 rows x 5 columns]

In [31]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1 : ].values

In [32]:
X 
Y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [34]:
#split the test set and the train set
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)
#lets train the data
from sklearn.linear_model import LogisticRegression
model_iris=LogisticRegression()
model_iris.fit(x_train,y_train)


c:\python\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\python\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [36]:
#now let's predict the test set and see the accuracy
y_predict = model_iris.predict(x_test)

In [37]:
def getAcurracy(y_predict,y_test):
    numberoftrue = 0
    count = 0
    for y in y_predict:
        if (y == y_test[count]):
            numberoftrue +=1
        count+=1
    return numberoftrue/count

In [39]:
print(getAcurracy(y_predict,y_test))

1.0


In [44]:
#let's use the classification evaluation metric
#First the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_predict)

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  6]], dtype=int64)

In the first column for all y value we predicted is 0, all of them has a value of 0 
In the second column for all y value we predicted is 1, all of them has a value of 1
In the third column for all y value we predicted is 2, all of them has a value of 2

all the non-diagonal value of the confusion_matrix are equal to 0 which means that our model has a 
accuracy of 100% is because of the iris dataset which is easy to predict.

In [72]:
#let's calculate the log loss for the model
from sklearn.metrics import log_loss
pred = model_iris.predict_proba(x_test) #get the probality of each class in each sample of y_predict

labels = iris.target_names
print("Log loss of the model: ",log_loss(y_test,pred,labels = labels)) #clculate the log loss

Log loss of the model:  0.0


c:\python\lib\site-packages\numpy\lib\arraysetops.py:608: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [ ]:
#log loss of 0 wich means that our model got an perfect accuracy

In [73]:
#now lets finish with f1score
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_predict, target_names=iris.target_names))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



f1score is equal to 1 for each class of the problem which means that the model has an accuracy of 100%